---
- name: This is a hello-world example
  hosts: localhost
  connection: local 

  vars_files:
    - config/sergey

  vars_prompt:

    - name: username
      prompt: What is your username?
      private: no

    - name: password
      prompt: What is your password?
  
  vars:
    hey: "{{ username | replace('-','_') }}"

  tasks:

    - name: Print a message
      ansible.builtin.debug:
        msg: 'Logging in as {{ username }} at {{ hey }}'

    - name: Copy favicon ico.
      copy:
        content: "{{ username }}"
        dest: tmp/yes