---
- name: This is a hello-world example
  hosts: localhost
  connection: local 

  vars_files:
    - config/sergey

  tasks:
    - name: check for sergey app
      rename: 
        src: "{{ one }}"
        dest: "{{ two }}"