---
- name: This is a hello-world example
  hosts: localhost
  connection: local 

  vars_files:
    - config/sergey

  tasks:
    - name: check for sergey app
      stat: path={{ app_location }}
      register: sergey

    - name: exit if sergey app already exists with this name
      fail: msg="This sergey app already exists - edit sergey/vars with new info"
      when: sergey.stat.exists

    - name: Create root directory fo app.
      file:
        path: "{{ app_location }}"
        state: directory

    - name: Copy favicon ico.
      copy:
        src: sergey/favicon.ico
        dest: "{{ app_location }}/favicon.ico"

    - name: Create sergey src directory.
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - '{{ app_location }}/src'
      
    - name: Copy headers.
      copy:
        src: sergey/headers
        dest: "{{ app_location }}/headers"

    - name: Ansible copy sergey files.
      copy:
        src: sergey/files
        dest: "{{ app_location }}"
    
    - name: Ansible copy sergey imports.
      copy:
        src: sergey/_imports
        dest: "{{ app_location }}"

    - name: Create package.json.
      template:
        src: sergey/package.json.j2
        dest: "{{ app_location }}/package.json"

    - name: Copy index.html.
      copy:
        src: sergey/index.html
        dest: "{{ app_location }}/index.html"

    - name: Install packages based on package.json.
      npm:
        path: "{{ app_location }}"

    - name: Copy sergey html file.
      template:
        src: sergey/first.html.j2
        dest: "{{ app_location }}/_imports/sections/first.html"
