---
- hosts: cloud
  become: true

  vars_files:
    - vars/server

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted

  tasks: 
    - name: chown to username you login and chmod as required
      file:
        path: /var/www/html
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: 0755

    - name: Cloning oh-my-zsh
      git:
        repo=https://github.com/robbyrussell/oh-my-zsh
        dest=~{{ deploy_user }}/.oh-my-zsh
  
    - name: Copy zshenv
      copy:
        src: server/zshenv
        dest: ~{{ deploy_user }}/.zshenv
    
    - name: Copy zshrc
      copy:
        src: server/zshrc
        dest: ~{{ deploy_user }}/.zshrc

    - name: Copy zsh theme
      copy:
        src: server/cerico.zsh-theme
        dest: ~{{ deploy_user }}/.oh-my-zsh/themes/cerico.zsh-theme
   
    - name: Copy motd
      copy:
        src: server/motd
        dest: /etc/profile.d/motd.sh
  
    - name: change user shell to zsh 
      become: yes
      user:
        name: "{{ deploy_user }}"
        shell: /bin/zsh