export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="cerico"

plugins=(git)

source $ZSH/oh-my-zsh.sh

source $HOME/.zshenv

eval "$(rbenv init - zsh)"
sh /etc/profile.d/motd.sh
sh /etc/profile.d/pm2.sh
sh /etc/profile.d/passenger.sh