---
- name: check for rails app
  stat: path=/etc/letsencrypt/live/{{ url }}
  register: cert

- name: check for rails app
  stat: path=/etc/letsencrypt/renewal/{{ url }}.conf
  register: certu

- name: exit if rails app already exists with this name
  fail: msg="This cert already exists dont worry about it"
  when: cert.stat.exists

- name: exit if rails app already exists with this name
  fail: msg="This cert already exists dont worry about it"
  when: certu.stat.exists

- name: stop nginx
  service: name=nginx state=stopped

- name: encrypt
  become: yes
  command: >
    /usr/bin/letsencrypt certonly --standalone -d {{ url }}

- name: start nginx
  service: name=nginx state=started